### PR TITLE
[FIX] Spam X to get out of vehicle, run, or aim

### PR DESCRIPTION
**Pull request by jnccloud**
**Problem:**
When raising your hands, sometimes another animation plays and the player doesn't recognize the need to cancel the hands up action. This results in the player being unable to run, aim or drive. 

**Solution:**
This PR adds a listener to re-enable the disabled controls after having your hands raised. It's automatic by listening for the hands up animation to end. There is no ms added when not in use because the thread is only created when hands are up, and ends when the hands up animation ends or another animation plays.

If your PR is to fix an issue mention that issue here: Can't find a GitHub issue, but plenty of Discord threads about it.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by jnccloud** [comment]
Discord threads with demonstrated uses:
https://discord.com/channels/831626422232678481/1051985374601297993

**Comment by jlinkous94** [comment]
Have been testing this on my server all day today. Have had no issues getting out of cars, shooting, or aiming. Seems this PR has fixed the issues for me. Thank you @jnccloud

**Comment by jnccloud** [comment]
Updated to merge with latest qb-smallresource commits

**Review by Irishstevie — APPROVED** [review]
This has fix the issue :)

**Comment by jnccloud** [comment]
@Z3rio - I've pulled the upstream changes for this PR again to catch it up with main, there are still a lot of people suffering from this and the fix still works. You can see all of the feedback in the links above and latest comments. Any chance you can get this in so people don't have to search PRs for it? Thanks!

**Comment by AnishBplayz** [comment]
Resolve the conflicts to merge

**Comment by jnccloud** [comment]
> Resolve the conflicts to merge

I've resolved conflicts at least 3 times now since I opened this. I resolved the conflict again today but the Lint checker is broken. Someone will have to manually review the change. This fixes a major annoyance bug in QB so if after 6 months no one wants to incorporate it, I can just close it.

**Pull request closed without merging**
