### PR TITLE
Fix for the Police weapon draw not working

### PR DESCRIPTION
**Pull request by N4PK1NZZz**
This PR fixes the police Weapon draw animation not working since the new update

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by KC-1508** [comment]
Thanks, this resolved the issue.

**Review by jaylac2000 — APPROVED** [review]

**Comment by RedhoodCH** [comment]
https://user-images.githubusercontent.com/119758263/206894630-0463a7f8-a33d-4b17-a3f3-4160fab536a9.mp4

I got this issue how can I fixed? But will out hostler swap weapon not roll back.

**Comment by JordanBScott** [comment]
I am still not able to have an animation for it. It just spawns the gun in my hand...

**Comment by jaylac2000** [comment]
you have custom weapons not properly set than

**Pull request closed without merging**
