### PR TITLE
Create attachez_c

### PR DESCRIPTION
**Pull request by vanillla1**
add prop attach for item

### CODE REVIEW

**Comment by vanillla1** [comment]
https://ibb.co/djWJf8J
https://ibb.co/TTrT3FL
https://ibb.co/pKs1Zg0
https://ibb.co/xqJWK0v
https://ibb.co/VVwrmKh

It gives great effectiveness to the players
I think it will be a great addition to the project

**Comment by JericoFX** [comment]
did you write all this?, because i saw this before on a leaked qbcore server i think it was on cerberus version

**Comment by pushkart2** [comment]
better way to do it with the dpemotes.. you can easily set the props in dpemotes.. Dont need a whole new file just to attach props.

**Comment by vanillla1** [comment]
I don't know if this is a leaked version
I don't know if any of them have some rights
But it is on github
I think if it was leaked
have deleted it by github

**Comment by vanillla1** [comment]
im try write this
https://github.com/qbcore-framework/qb-smallresources/pull/30/commits/fe4321ac3e7ebb2ff0fd98ddc07fa945b4153ba8

**Pull request closed without merging**
