### PR TITLE
Support Dui Functions

### PR DESCRIPTION
**Pull request by darknight2590**
An example of the use through a video of one of the members of the project Snipe
https://www.youtube.com/watch?v=b92Sxsl1H10
Supports jpgs, pngs, gifs, videos

### CODE REVIEW

**Comment by ihyajb** [comment]
where did u get this code from?

**Comment by FjamZoo** [comment]
> where did u get this code from?

it starts with No and rhymes with Mixel

**Comment by darknight2590** [comment]
https://github.com/search?q=CreateRuntimeTextureFromDuiHandle

**Comment by BerkieBb** [comment]
> https://github.com/search?q=CreateRuntimeTextureFromDuiHandle

That doesn't help at all

**Comment by FjamZoo** [comment]
Questionable where the code came from, implementation can also be better. Closed with the mindset that this will be coming sooner or later we are just looking for a better implementation.

**Pull request closed without merging**
