### PR TITLE
fix(client): fix scuffed weapon holster animation while running. Fixes #290

### LINKED ISSUE #290: Rollback when switching weapon
Hey when i switch from weapon and i run during animation player were rollback

### PR DESCRIPTION
**Pull request by Griefa**
**Describe Pull request**
Fixes the issue of the rubber banding while rotating/running. This builds on PR #288 to include the correct rotation

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by tom-osborne — APPROVED** [review]

**Comment by Z3rio** [comment]
Could you please provide some sort of steps to reproduce this, or an video showing how to reproduce it.
I would assume it fixes an issue with being "rubber banding" upon moving whilst holstering an weapon, although upon testing it with the default qb-smallresources I dont seem to encounter such issue.

**Comment by Benzo00** [comment]
image

**Comment by tom-osborne** [comment]
> Could you please provide some sort of steps to reproduce this, or an video showing how to reproduce it. I would assume it fixes an issue with being "rubber banding" upon moving whilst holstering an weapon, although upon testing it with the default qb-smallresources I dont seem to encounter such issue.

To reproduce it, draw your weapon, while running and turning. You will see rubber banding. With this PR it removes the rubber banding and remains smooth motion.

**Comment by Z3rio** [comment]
> > Could you please provide some sort of steps to reproduce this, or an video showing how to reproduce it. I would assume it fixes an issue with being "rubber banding" upon moving whilst holstering an weapon, although upon testing it with the default qb-smallresources I dont seem to encounter such issue.
> 
> To reproduce it, draw your weapon, while running and turning. You will see rubber banding. PR #288 fixes the positional rubber banding but you still get the rotational element of it. This PR removes the rubber banding and remains smooth motion for position and rotation.

Yeah, that is what I assumed that it did, although it seems to be working fine for me upon using the default / current version of qb-smallresources aswell.
The video below shows me running in an circle (changing both the heading and position of my char) without any rubber banding on the position, nor rotation / heading.
https://streamable.com/v1zf69

**Comment by tom-osborne** [comment]
The only thing is it looks like you are not wearing a holster, since the gun is being pulled from the back.

I guess it is possible this was fixed with a different PR since this PR did have some conflicts. In which case this can be closed.

**Comment by Z3rio** [comment]
> The only thing is it looks like you are not wearing a holster, since the gun is being pulled from the back.
> 
> I guess it is possible this was fixed with a different PR since this PR did have some conflicts. In which case this can be closed.

Oh, yeah that might be it, I will retry it.

**Comment by Z3rio** [comment]
Upon testing it with an holster, it seems to be working fine aswell.
https://streamable.com/iy3mz6
So yeah, seems like this might have indeed already been fixed.

**Comment by Z3rio** [comment]
Closed until further reproductional steps are sent since by the looks of it (see conversation above) this has already been resolved by https://github.com/qbcore-framework/qb-smallresources/commit/844a84dddd56a7ef7db6870775b878de98333500 .

**Pull request closed without merging**
