### PR TITLE
closer blip

### PR DESCRIPTION
**Pull request by evanillaa**
The blip is hidden from the map and appears only when you approach the areas where the vehicle wash is

### CODE REVIEW

**Review by Slay3rIQ — APPROVED** [review]
Good patch. I think it also good to add this tho clothing, barber etc.

**Review by zfbx — CHANGES_REQUESTED** [review]
even if you remove the keys `[1], [2], etc` it'd be nice if you leave the labels for people who want to rename carwashes per location, it's a nice option to have available rather than just being hardcoded to one. also it opens up ability to add custom locations

**Comment by evanillaa** [comment]
Could you provide your favorite modification?
@zfbx

**Comment by zfbx** [comment]
Wait, looking deeper into this code, what is going on here? why is it a loop now when it wasn't before?

**Comment by GhzGarage** [comment]
Conflicts

**Comment by BerkieBb** [comment]
The blip is never created?

**Comment by evanillaa** [comment]
@BerkieBb hello bro
blip show look photo

		local closest = 1000
```
	while true do
		local coords = GetEntityCoords(PlayerPedId())
		local closest = 1000
		local closestCoords

		for _, carWashCoords in pairs(Config.CarWash) do
			local dstcheck = #(coords - carWashCoords)

			if dstcheck < closest then
				closest = dstcheck
				closestCoords = carWashCoords
			end
		end

		if DoesBlipExist(currentCarwashBlip) then
			RemoveBlip(currentCarwashBlip)
		end

		currentCarwashBlip = CreateBlip(closestCoords)
		Wait(10000)
	end

```

**Comment by BerkieBb** [comment]
I missed where it was created, you're good

**Comment by evanillaa** [comment]
> I missed where it was created, you're good

thank you so much

**Pull request closed without merging**
