### PR TITLE
[ENHANCEMENTS] Adding config options for dispatch services

### PR DESCRIPTION
**Pull request by charj**
Making dispatch services configurable.

**Fixes:**
https://github.com/qbcore-framework/qb-smallresources/issues/204

**Questions (please complete the following information):**
- [x] Tested?
- [x] Does your code fit the style guidelines?
- [x] Does your PR fit the contribution guidelines?

### CODE REVIEW

**Review by JulianW051 — COMMENTED** [review]
I tested the script first by enabling FireDepartment and blowing up some vehicles. this did nothing and no fire responded. 
I then decided to enable everything in the config, go to grove street and start shooting. The gang member around me just walked away or did nothing and I was attacked by two dogs.
This shows that putting the values to true does not seem to actually enable the dispatch service.

**Comment by r0adra93** [comment]
You need to add comments above the config and instructing what to do with the values!
Setting them to true DISABLES the feature instead of enabling the feature!
No one would know unless you let people know!

**Comment by charj** [comment]
> This shows that putting the values to true does not seem to actually enable the dispatch service.
Added a comment

> I tested the script first by enabling FireDepartment and blowing up some vehicles. this did nothing and no fire responded. I then decided to enable everything in the config, go to grove street and start shooting. The gang member around me just walked away or did nothing and I was attacked by two dogs. This shows that putting the values to true does not seem to actually enable the dispatch service.

I'll do some further investigation, thanks for testing.

**Review by Z3rio — APPROVED** [review]
Great PR, although I disliked the way you were doing those for loops.
I hope its okay that I improved them a little, thank you for your PR!

**Comment by Z3rio** [comment]
I tested this, yeah.

**Pull request merged**
