### PR TITLE
Duplicate Config.

### PR DESCRIPTION
**Pull request by iktray**
**Describe Pull request**
Duplicate config option for hud components.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by Ranjit-Develops — APPROVED** [review]

**Comment by tom-osborne** [comment]
@iktray Can you elaborate on why you feel it is necessary to remove those config options? Where exactly are they duplicated?

@Ranjit-Develops why did you approve this PR?

**Comment by Ranjit-Develops** [comment]
@tom-osborne 
I approved this because I had seen one more of this too it's because the qb-hud have it

**Comment by tom-osborne** [comment]
> @tom-osborne 
> I approved this because I had seen one more of this too it's because the qb-hud have it

Right, but qb-smallresources makes use of these config options, so assuming qb-hud does the same thing, you would not only need to remove the config options but also check everywhere they are used. Otherwise, you will get errors when the script is executed.

**Comment by Ranjit-Develops** [comment]
You are Right It's My mistake I should Have check for config in client.lua and server.lua
I apologise For It 
Will Never happen It near future

**Comment by SKITTLE6969** [comment]
Its duplicated inside the config so won't be an issue 
image

**Comment by tom-osborne** [comment]
> @tom-osborne Its duplicated inside the config so won't be an issue image

Perfect, thank you @SKITTLE6969 that's all both of the other two had to explain.

**Comment by iktray** [comment]
@tom-osborne Hey, I was away from my computer during the holiday. It was pretty simple it was a duplicated config.

**Comment by tom-osborne** [comment]
> @tom-osborne Hey, I was away from my computer during the holiday. It was pretty simple it was a duplicated config. 

Yep, understood. Good idea to reference exactly where they are duplicated next time to make it easier for the person reviewing

**Comment by SKITTLE6969** [comment]
it didn't cause any issues when i tested but better we merge this at earlierst possible 

> > @tom-osborne Its duplicated inside the config so won't be an issue image
> 
> Perfect, thank you @SKITTLE6969 that's all both of the other two had to explain.

**Review by charj — CHANGES_REQUESTED** [review]
`Config.Disable` does not appear duplicated

**Comment by tom-osborne** [comment]
> `Config.Disable` does not appear duplicated

It most definitely is.

https://github.com/qbcore-framework/qb-smallresources/blob/main/config.lua#L69

https://github.com/qbcore-framework/qb-smallresources/blob/main/config.lua#L98

**Comment by charj** [comment]
Ah yeah! xD

**Review by Z3rio — APPROVED** [review]

**Pull request merged**
