### PR TITLE
Melee weapons fix

### PR DESCRIPTION
**Pull request by AnishBplayz**
So there was an error with my previous PR and I didn't notice but with the pistol whipping being removed the native also removes  the ability for player not being able to use melee weapons so including fixing this and  to make sure the code works as required i also added an else check for optimization

### CODE REVIEW

**Comment by GhzGarage** [comment]
I noticed your edit for optimization calls the PlayerPedId() three times instead of calling it once and just refreshing the variable

**Comment by AnishBplayz** [comment]
@GhzGarage I localised the PlayerPedId() Variable now... shouldn't be an issue now

**Comment by GhzGarage** [comment]
You put it outside the loop

**Comment by AnishBplayz** [comment]
It is outside the loop

**Pull request closed without merging**
