### PR TITLE
Made tagEveryone into a string and changed it to tag

### PR DESCRIPTION
**Pull request by r0adra93**
Converted tagEveryone boolean into a string. If the variable is set to false or nil it will still process through.
It will leave a  console message if the tag is a boolean instead of a string containing the name of the group like admin or the dreaded everyone.

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Review by Jorn08 — CHANGES_REQUESTED** [review]
One of the parameters of the log event is to toggle between tagging everyone or not, just pass it false if you don't want an @ everyone instead of deprecating it

**Comment by tom-osborne** [comment]
@r0adra93 So what do we do if people do want to tag everyone?

It's already configurable as @Jorn08 pointed out, so if you don't want it then disable it. I don't see the point in this PR, please close.

**Comment by r0adra93** [comment]
> @r0adra93 So what do we do if people do want to tag everyone?
> 
> It's already configurable as @Jorn08 pointed out, so if you don't want it then disable it. I don't see the point in this PR, please close.

it's a bullshit tag I can look into modifying it to allow @everyone to be set to w/e they want it to be and just filter out "true"

**Comment by tom-osborne** [comment]
Adding an extra config option to be able to select which tag ID would be a neater solution. 

The code tagging everyone in your discord is on you though. If it is setup right, you wouldn't get that issue. Doing a global fix to remove a feature off the back of that is not correct.

**Comment by r0adra93** [comment]
> Adding an extra config option to be able to select which tag ID would be a neater solution.
> 
> The code tagging everyone in your discord is on you though. If it is setup right, you wouldn't get that issue. Doing a global fix to remove a feature off the back of that is not correct.

I solved the issue with the core tagging EVERYONE. I wanted to prevent this out of a raging temper as some dodo tagged "everyone" in a log within the core itself. It was pushed through which was even worse! So I threw the baby out with the bathwater. I fixed it though.

**Pull request closed without merging**
