### PR TITLE
harness error fix while 1st time use

### PR DESCRIPTION
**Pull request by ARSSANTO**

### CODE REVIEW

**Review by amantu-qbit — APPROVED** [review]
Perfectly

**Review by amantu-qbit — COMMENTED** [review]
Doesn't Fix it. @ARSSANTO @GhzGarage

**Comment by ARSSANTO** [comment]
it was not showing error when  me and @amantu-qbit  was in vc then after 1 day we again test it same error i think need a rewrite

**Comment by amantu-qbit** [comment]
> it was not showing error when  me and @amantu-qbit  was in vc then after 1 day we again test it same error i think need a rewrite

Exactly

**Pull request merged**
