### PR TITLE
Updated Carwash

### PR DESCRIPTION
**Pull request by JericoFX**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

 **Change the carwash to Polyzones**

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] **(YES)**
- Does your code fit the style guidelines? [yes/no] **i think**
- Does your PR fit the contribution guidelines? [yes/no] **yes**

### CODE REVIEW

**Comment by zwkf** [comment]
Please fix conflicts with this branch

**Review by zwkf — CHANGES_REQUESTED** [review]
Please fix conflicts with this branch

**Comment by JericoFX** [comment]
this is really old and there was another merge that kinda did the same

**Comment by zwkf** [comment]
Closed - issue fixed with another PR

**Pull request closed without merging**
