### PR TITLE
FIX Issue #313, #327, #321 and #324

### LINKED ISSUE #327: [BUG] parachute stays on the back
**Describe the bug**
   1- #321 
   2- When you land on the ground after using the parachute, it stays on your back.

**To Reproduce**
- #321  see Issue post

- When you land on the ground after using the parachute, it stays on your back.
https://www.youtube.com/watch?v=7pM87DMmzP4

**Expected behavior**
When it reaches the ground, the parachute is removed. 

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

### PR DESCRIPTION
**Pull request by Bakisito**
**Describe Pull request**
Added the option to activate the reticle with native ShowHudComponentThisFrame only when using a sniper rifle.
https://docs.fivem.net/natives/?_0x0B4DF1FA60C0E664
image

If your PR is to fix an issue mention that issue here
#313 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

Add  new commits 
4be88ba5a4b7dc7e5a04b99ec1b00842ca7bd75b
To fix #327  and #321 

Describe Pull request
Fix title "qb-smallpenis:server:AddParachute" To "consumables:server:AddParachute"

Add a thread to get the current state of the player's parachute at any time. You can use an if condition to check if the parachute state is 3: Falling to doom. and if so, call TriggerEvent('qb-clothing:client:loadOutfit', ParachuteRemoveData) to remove the prop from the player's parachute.

Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
Does your code fit the style guidelines? yes
Does your PR fit the contribution guidelines? yes

Move PR  https://github.com/qbcore-framework/qb-smallresources/pull/324 here

### CODE REVIEW

**Comment by Bakisito** [comment]
Added new commits

**Comment by Bakisito** [comment]
Moving new commits of #324 here

**Comment by McKlean** [comment]
I believe `getisInHospitalBed()` should be `isInHospitalBed()` however, this does call an error saying no such export

**Comment by Bakisito** [comment]
> I believe `getisInHospitalBed()` should be `isInHospitalBed()` however, this does call an error saying no such export

is because this is a variable that is already declared, but the export is not created, so I made an export of that variable in this PR
https://github.com/qbcore-framework/qb-ambulancejob/pull/265

**Comment by BlackDahlia313** [comment]
https://github.com/qbcore-framework/qb-smallresources/pull/326/commits/a693c6c435722fa1f0414642045651ffeb8536d7

needed this snippet ty

**Pull request closed without merging**
