### PR TITLE
[FIX] Fixing 'rubberband' issue.

### PR DESCRIPTION
**Pull request by WooshieBurr**
Fixing a rubberbanding issue where a new position wasn't declared after the wait, so you teleported back with TaskPlayAnimAdvanced using old position data.

### CODE REVIEW

**Comment by Xoogle5M** [comment]
> Fixing a rubberbanding issue where a new position wasn't declared after the wait, so you teleported back with TaskPlayAnimAdvanced using old position data.

I've implemented this, but still teleport when switching weapons, unfortunately. Would you mind sending your full weapdraw code?

**Comment by NeonLifeRPde** [comment]
Just Download His qb-smallresources?

**Comment by NeonLifeRPde** [comment]
> > Fixing a rubberbanding issue where a new position wasn't declared after the wait, so you teleported back with TaskPlayAnimAdvanced using old position data.
> 
> I've implemented this, but still teleport when switching weapons, unfortunately. Would you mind sending your full weapdraw code?

Just Download His qb-smallresources?

**Comment by Holidayy95** [comment]
Doesn't work

**Review by Z3rio — APPROVED** [review]
Unsure if this really fixes anything.
But judging from the code, it looks fine.
I will have to test it ingame when I'm home.

**Comment by Griefa** [comment]
> Unsure if this really fixes anything. But judging from the code, it looks fine. I will have to test it ingame when I'm home.

Yeah, it doesn't fix anything. Why are you even improving stuff without testing it? Clearly you can't read code properly because this "fix" didn't fix anything in the first place

**Comment by Z3rio** [comment]
> > Unsure if this really fixes anything. But judging from the code, it looks fine. I will have to test it ingame when I'm home.
> 
> Yeah, it doesn't fix anything. Why are you even approving stuff without testing it? Clearly you can't read code properly because this "fix" didn't fix anything in the first place

I approved that the code looks good and that there shouldnt be any errors or such with it. Which you would have seen if you read the text in the approving.
And judging from the code, the possibillity that this fixes something does exist considering what is said in the initial PR text.
No need to be aggressive, as you can see the PR hasnt been commited for the exact reason you noted above, that it doesnt seem to fix anything.

**Review by Z3rio — CHANGES_REQUESTED** [review]
Not reproduceable from the info in the PR. Please follow the template for PRs.
When trying to draw a weapon on my own server, I dont encounter this issue at all, please include more information on how to recreate this issue, or perhaps a video of the issue and I will gladly test this further.

**Pull request closed without merging**
