### PR TITLE
It is very important to classify items

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by zfbx** [comment]
Why is this "very important" does it serve a purpose?

**Comment by evanillaa** [comment]
Yes, increase the rating further

**Comment by phumberdroz** [comment]
I am not sure if I understand the purpose of this MR

**Comment by evanillaa** [comment]
> 
> 
> I am not sure if I understand the purpose of this MR

The idea of the distribution is to make the code more transparent
There is a lot to learn
This is useful for them so that they can understand the code more clearly
Why should we close the code and not rewrite it more clearly?
I feel a lot of people will be happy with this because it is well distributed

**Review by Eralpozcan — APPROVED** [review]
It works nicely and improves readability.

**Comment by evanillaa** [comment]
> 
> 
> It works nicely and improves readability.

Yes, that is what I wanted to say with this modification
Improve comprehension and reading
thank you for replay

**Pull request closed without merging**
