### PR TITLE
no handsup if dead or last stand

### PR DESCRIPTION
**Pull request by Bakisito**
handsup
In addition to not being able to raise his hand when handcuffed, also not being able to raise his hand when he is in last stand or dead.

**Describe Pull request**
I added that you can avoid raising your hand when the character is dead or in last stand, I think it helps to avoid the annoying spam of raising your arms many times when the character is on the ground.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by Bakisito** [comment]
:)

**Comment by Muri22** [comment]
can you  make it for ambulance bed also player when they on bed they can do x

**Comment by Bakisito** [comment]
> can you make it for ambulance bed also player when they on bed they can do x

yeah thats easy, gimme a sec

**Comment by Bakisito** [comment]
done! @Muri22

**Comment by Bakisito** [comment]
I have a mess.. the commit i just made is on #326. Closing this one and moving everything there!

**Comment by Bakisito** [comment]
I have a mess.. the commit i just made is on #326. Closing this one and moving everything there!

**Pull request closed without merging**
