### PR TITLE
fix(tackle): Add missing param

### PR DESCRIPTION
**Pull request by Sharkiiie**
Add a missing param to RegisterCommand.
I believe this should fix the linting issue.

### CODE REVIEW

**Comment by Sharkiiie** [comment]
Guess not :P

**Comment by AnishBplayz** [comment]
LGTM

**Review by AnishBplayz — APPROVED** [review]
LGTM

**Comment by GhzGarage** [comment]
The restricted bool is not used on the client side. Permissions can only be checked on the server side

**Comment by AnishBplayz** [comment]
But i still have seen people using  it in client side which infact shouldn't matter so i guess either we can close this PR as unnecessary or either merge it shouldn't affect anything i say

**Pull request closed without merging**
