### PR TITLE
not important

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by zfbx** [comment]
can you elaborate on how and why this is no important?..

**Comment by evanillaa** [comment]
Can you tell me how important it is?

**Comment by zfbx** [comment]
No, cause I can't test it at the moment but you've submitted a PR saying it's not important? Have you checked what models it's removing and where to see why it may of been created in the first place?

**Comment by evanillaa** [comment]
Yes in the garage in the city center
It doesn't matter, I think it's better to remove it
This is the opinion of most programmers on Discord when the question was asked

**Comment by zfbx** [comment]
Can you link to messages about these comments? I only see one mention of `removeentities.lua` and it was someone looking for how to add prop removal 🤔

**Pull request closed without merging**
