### PR TITLE
ci(seatbelt): pass seatbeltOn boolean as a param when calling the seatbelt:client:ToggleSeatbelt event

### PR DESCRIPTION
**Pull request by vipexv**
Why are we not passing the `seatbeltOn` bool as a param when calling the `seatbelt:client:ToggleSeatbelt` event, like what is the benefit in not doing that?

This change simply passes it as a param, and it doesn't break anything, it simply adds an extra feature, and it is an optional param that players/developers can use to make their life easier.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by Qwerty1Verified** [comment]
I don't mind the idea, could be helpful for clear declaration of data being derived from one source. I do want to know which use case you see for this to be a functional improvement for since you mentioned it's an extra feature?

**Comment by vipexv** [comment]
I was working on a commission recently, and i found it to be easier to just handle it this way, it just generally doesn't have any cons to it, it only brings benefits and makes things easier.

**Comment by Qwerty1Verified** [comment]
Yeah that's what I'm referring to I'd just like to hear your use case on it to know how you used it and how it helped you.

**Comment by vipexv** [comment]
Most of my issues weren't really an issue with QB, it was mainly with OOP in LUA, and syncing states between instances, it was just behaving weirdly since LUA isn't really made for OOP, although you can simulate it using metatables(somewhat,  and i was having some difficulty syncing this state due to the way it was behaving, i did manage to resolve it, and it was an issue with the way i wrote it, but in the end i did manage to resolve the issue itself, but i still went ahead and passed the seatbeltOn bool as a param, to me it feels like it would be a better solution that developers can optionally make use of?

**Comment by vipexv** [comment]
Even when your storing a variable, i personally would it rather pass it as a prop/argument.

**Comment by Qwerty1Verified** [comment]
Sounds good, just wanted to make sure it had an actual use case. Although it could be said that state desync isn't a big issue since resources shouldn't really be restarted in "production", I do often argue that if need be then sometimes it must happen for the show to roll on. Then there's the other use case I can think of where you're just handing it off to a UI and don't want to worry about storing it, and updating it.

**Comment by vipexv** [comment]
For me, it's more convenient this way, and it doesn't cost or break anything, which is mostly the primary reason for the suggestion, it simply adds something extra which doesn't break compatibility at all, and can optionally be used.

**Comment by Qwerty1Verified** [comment]
Yes, it's more of a development quality of life change.

**Review by Qwerty1Verified — APPROVED** [review]

**Pull request merged**
