### PR TITLE
Add alot more vehicles & peds to blacklist

### PR DESCRIPTION
**Pull request by SPKReality**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

1.) Yes
2.) Yes
3.) Yes

### CODE REVIEW

**Comment by tom-osborne** [comment]
This would break since you have changed the keys from hashes (using ` back ticks) to strings.

This table is used here:https://github.com/qbcore-framework/qb-smallresources/blob/main/server/entities.lua#L4

The key used is the value returned by [GetEntityModel()](https://docs.fivem.net/natives/?_0x9F47B058362C84B5), which returns the hash, so you need to use backticks to convert the string to a hash.

**Comment by SPKReality** [comment]
Should be fine now mate

**Comment by McKlean** [comment]
Why are you blacklisting perfectly good vehicles?
Motorbikes, Issi, there are some perfectly good vehicles in their that doesn't need to be blacklisted at all

**Comment by SPKReality** [comment]
Just went through alot of vehicle models and added them so I may have added wrong ones too

**Comment by tom-osborne** [comment]
Agree, I don't see the point in this PR if you have added these for no reason.

**Pull request closed without merging**
