### PR TITLE
New Density Adjustment

### PR DESCRIPTION
**Pull request by darknight2590**
New Density Adjustment It gives you more freedom to deal and add more options

### CODE REVIEW

**Comment by BerkieBb** [comment]
Did you get this code from somewhere?

**Comment by amantu-qbit** [comment]
Wait what?

**Comment by IdrisDose** [comment]
Can you explain the code and what exact function it serves? Why is this better than the current one? And why are you touching decorators? You need to explain the code, please.

**Comment by KingRyuShin** [comment]
I think doing it like this would be way better than all this code..

```
TrafficAmount = 23
PedestrianAmount = 75
ParkedAmount = 28
EnableBoats = true
EnableTrains = false

-- Stops vehicles from spawning that cause issues in OneSync
Citizen.CreateThread(function()
	EnableDispatchService(1, false)
	EnableDispatchService(2, false)
	EnableDispatchService(3, false)
	EnableDispatchService(4, false)
	EnableDispatchService(5, false)
	EnableDispatchService(6, false)
	EnableDispatchService(7, true)
	EnableDispatchService(8, false)
	EnableDispatchService(9, false)
	EnableDispatchService(10, false)
	EnableDispatchService(11, true)
	EnableDispatchService(12, false)
	EnableDispatchService(13, false)
	EnableDispatchService(14, false)
	EnableDispatchService(15, false)
	while true do
		Wait(0)
		SetVehicleDensityMultiplierThisFrame((TrafficAmount/100)+.0)
		SetPedDensityMultiplierThisFrame((PedestrianAmount/100)+.0)
		SetRandomVehicleDensityMultiplierThisFrame((TrafficAmount/100)+.0)
		SetParkedVehicleDensityMultiplierThisFrame((ParkedAmount/100)+.0)
		SetScenarioPedDensityMultiplierThisFrame((PedestrianAmount/100)+.0, (PedestrianAmount/100)+.0)
		SetRandomBoats(EnableBoats)
		SetRandomTrains(EnableTrains)
        SetVehicleModelIsSuppressed(GetHashKey("rubble"), true)
        SetVehicleModelIsSuppressed(GetHashKey("dump"), true)
        SetVehicleModelIsSuppressed(GetHashKey("taco"), true)
        SetVehicleModelIsSuppressed(GetHashKey("biff"), true)
        SetVehicleModelIsSuppressed(GetHashKey("blimp"), true)
    end
end)
```

**Comment by BerkieBb** [comment]
It would not be

**Pull request closed without merging**
