### PR TITLE
Teleport Update

### PR DESCRIPTION
**Pull request by Frutaz**
With this update u will be able to teleport walking and on vehicles.

### CODE REVIEW

**Comment by BerkieBb** [comment]
Maybe make a parameter for the location like 'usevehicle' and if that's true then you can use this way, otherwise you would be able to teleport to places you should only be able to walk to which you probably don't want

**Comment by Frutaz** [comment]
Ok, thanks for the suggest, can I update the pull request or I gotta do
another one?

**Comment by BerkieBb** [comment]
You can update it

**Comment by BerkieBb** [comment]
Just go to your fork and then the branch patch-1 and update, every change you make there will be put into this pr

**Comment by BerkieBb** [comment]
I'm going to make this myself now so I'll close this

**Pull request closed without merging**
