### PR TITLE
Removed handsup on bikes and motorcycles

### PR DESCRIPTION
**Pull request by clementinise**
You can't "handsup" on bikes and motorcycles since the animation is bugged when on those vehicle. Also, on motorcycles you can use "X" to do other things like use a melee weapon to hit others, etc. It was hard to use "X" on bikes since it's stopped steering and the animation was bugged :(

### CODE REVIEW

**Comment by GhzGarage** [comment]
Has conflicts now

**Comment by GhzGarage** [comment]
Has conflicts now

**Comment by clementinise** [comment]
Conflict resolved and if player is climbing while trying to handsup, he will fall (ragdoll)

**Comment by GhzGarage** [comment]
Conflicts

**Pull request closed without merging**
