### PR TITLE
Recode + Permissions Fix

### PR DESCRIPTION
**Pull request by ItsANoBrainer**

### CODE REVIEW

**Comment by milotiro95** [comment]
Had error with this ❌ 
Sans titre

**Comment by BerkieBb** [comment]
And that you have qb-core updated

**Comment by milotiro95** [comment]
I have this in my afk server and I believe to have qb-core update I have push the main fews days ago while the realease the 1.0.0 one

**Comment by BerkieBb** [comment]
You need qb-core 1.1.0 for this to work

**Comment by milotiro95** [comment]
True i was missed some files after hour of research all looks great now !

**Comment by milotiro95** [comment]
I tried with qb-smallresources server/entities to put the perms for enable admin to spawn some blacklisted cars. It looks like it's working. But can you confirm to me if it's good before I merge or perhaps @ItsANoBrainer can add to his branch ? 

```
local QBCore = exports['qb-core']:GetCoreObject()

-- Blacklisting entities can just be handled entirely server side with onesync events
-- No need to run coroutines to supress or delete these when we can simply delete them before they spawn
AddEventHandler("entityCreating", function(handle)
    local entityModel = GetEntityModel(handle)

    if checkUser and Config.BlacklistedVehs[entityModel] or Config.BlacklistedPeds[entityModel] then
        CancelEvent()
    end
end)
```

**Review by BerkieBb — APPROVED** [review]

**Comment by BerkieBb** [comment]
Added in #250

**Pull request closed without merging**
